controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: Infrastructure\Http\Controller
    type: attribute

manager:
    resource:
        path: ../src/Http/Controller/Manager/
        namespace: Infrastructure\Http\Controller\Manager
    type: attribute
    prefix: /manager
