controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: Infrastructure\Http\Controller
    type: attribute

manager:
    resource:
        path: ../src/Http/Controller/Manager
        namespace: Infrastructure\Http\Controller\Manager
    type: attribute

api:
    resource:
        path: ../src/Http/Controller/Api
        namespace: Infrastructure\Http\Controller\Api
    type: attribute
